
ROWS = 6
COLUMNS = 7
NUM_BITS_PER_COLUMN = len(bin(ROWS)[2:]) + ROWS
MAX_BITS_PER_STATE = NUM_BITS_PER_COLUMN * COLUMNS
print(NUM_BITS_PER_COLUMN)
print(MAX_BITS_PER_STATE)
CELL_SIZE = 120

MINIMAX = "Minimax"
MINIMAX_PRUNE = "Pruning"
EXPECTI = "Expecti"

WIDTH = COLUMNS * CELL_SIZE
HEIGHT = ROWS * CELL_SIZE

EMPTY = 0 
HUMAN = 1
AI = 2